application: helloworld
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /tasks/grab/.*
  script: _go_app
  login: admin

- url: /images
  static_dir: statics/images

